// Code generated by goctl. DO NOT EDIT!
// Source: borrow-rpc.proto

package server

import (
	"context"

	"library/app/borrow/rpc/borrow"
	"library/app/borrow/rpc/internal/logic"
	"library/app/borrow/rpc/internal/svc"
)

type SearchAllServer struct {
	svcCtx *svc.ServiceContext
	borrow.UnimplementedSearchAllServer
}

func NewSearchAllServer(svcCtx *svc.ServiceContext) *SearchAllServer {
	return &SearchAllServer{
		svcCtx: svcCtx,
	}
}

func (s *SearchAllServer) SearchAll(ctx context.Context, in *borrow.BorrwoIdReq) (*borrow.BorrowListResp, error) {
	l := logic.NewSearchAllLogic(ctx, s.svcCtx)
	return l.SearchAll(in)
}
