// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"library/app/search/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Example},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/search/do",
					Handler: searchHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/search/add",
					Handler: addHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
