// Code generated by goctl. DO NOT EDIT!
// Source: borrow-rpc.proto

package searchall

import (
	"context"

	"library/app/borrow/rpc/borrow"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BorrowInfoResp = borrow.BorrowInfoResp
	BorrowListResp = borrow.BorrowListResp
	BorrwoIdReq    = borrow.BorrwoIdReq

	SearchAll interface {
		SearchAll(ctx context.Context, in *BorrwoIdReq, opts ...grpc.CallOption) (*BorrowListResp, error)
	}

	defaultSearchAll struct {
		cli zrpc.Client
	}
)

func NewSearchAll(cli zrpc.Client) SearchAll {
	return &defaultSearchAll{
		cli: cli,
	}
}

func (m *defaultSearchAll) SearchAll(ctx context.Context, in *BorrwoIdReq, opts ...grpc.CallOption) (*BorrowListResp, error) {
	client := borrow.NewSearchAllClient(m.cli.Conn())
	return client.SearchAll(ctx, in, opts...)
}
