// Code generated by goctl. DO NOT EDIT.
package types

type Hisreq struct {
	Tag bool `form:"tag"`
}

type Hisresp struct {
	UserId     string `json:"userId"`
	BookId     string `json:"bookId"`
	IsReturn   int32  `json:"isReturn"`
	BorrowTime string `json:"borrowTime"`
	ReturnTime string `json:"returnTime"`
}

type HistoryListResp struct {
	List []Hisresp `json:"list"`
}
