// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Id       string `form:"id"`
	Password string `form:"password"`
}

type LoginResq struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type SignupReq struct {
	Id       string `form:"id"`
	Password string `form:"password"`
	Name     string `form:"name"`
	Gender   string `form:"gender"`
}

type SingupResq struct {
	Ok bool `json:"ok"`
}
