// Code generated by goctl. DO NOT EDIT.
package types

type BorrowReq struct {
	Name string `form:"name"`
}

type BorrowResq struct {
	Status bool `json:"ok"`
}

type ReturnReq struct {
	Name string `form:"name"`
}

type ReturnResq struct {
	Status bool `json:"ok"`
}
