// Code generated by goctl. DO NOT EDIT!
// Source: search.proto

package server

import (
	"context"

	"library/app/search/rpc/internal/logic"
	"library/app/search/rpc/internal/svc"
	"library/app/search/rpc/search"
)

type SearchServer struct {
	svcCtx *svc.ServiceContext
	search.UnimplementedSearchServer
}

func NewSearchServer(svcCtx *svc.ServiceContext) *SearchServer {
	return &SearchServer{
		svcCtx: svcCtx,
	}
}

func (s *SearchServer) Search(ctx context.Context, in *search.SearchReq) (*search.SearchResp, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}

func (s *SearchServer) Borrow(ctx context.Context, in *search.BorrowReq) (*search.BorrwoResp, error) {
	l := logic.NewBorrowLogic(ctx, s.svcCtx)
	return l.Borrow(in)
}

func (s *SearchServer) Return(ctx context.Context, in *search.ReturnReq) (*search.ReturnResp, error) {
	l := logic.NewReturnLogic(ctx, s.svcCtx)
	return l.Return(in)
}
