// Code generated by goctl. DO NOT EDIT.
package types

type SearchReq struct {
	Name string `form:"name"`
}

type SearchResp struct {
	Name      string `json:"name"`
	Count     int    `json:"count"`
	Count_now int    `json:"count_now"`
}

type AddReq struct {
	Name  string `form:"name"`
	Count int    `form:"count"`
}

type AddResp struct {
	Ok bool `json:"ok"`
}
