// Code generated by goctl. DO NOT EDIT!
// Source: login-rpc.proto

package loginclient

import (
	"context"

	"library/app/login/rpc/login"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IdReq  = login.IdReq
	IdResp = login.IdResp

	Login interface {
		Login(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*IdResp, error)
	}

	defaultLogin struct {
		cli zrpc.Client
	}
)

func NewLogin(cli zrpc.Client) Login {
	return &defaultLogin{
		cli: cli,
	}
}

func (m *defaultLogin) Login(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*IdResp, error) {
	client := login.NewLoginClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
